name : Hello World 2

# Events

on:
  push:
    branches:
      -main

  pull_request:
    branches:
      -main

      workflow_dispatch:


      # Workflow / Jobs

  jobs:
    hello:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -name: Hello World 2
       run: echo "Hello World 2"
       shell: bash
      
